// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCexInfdWgCXIVvsgMs2DCiv4UkbE5AChI',
    appId: '1:488612459446:web:c5e8e6dd44b18da2794717',
    messagingSenderId: '488612459446',
    projectId: 'kutubfm-1ef89',
    authDomain: 'kutubfm-1ef89.firebaseapp.com',
    storageBucket: 'kutubfm-1ef89.firebasestorage.app',
    measurementId: 'G-0Q2S9Y3DDG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA65UlQGyw_B5WUACVFjSxCKNZ_Tz7qSrE',
    appId: '1:488612459446:android:f59b6a1be1bfe8f1794717',
    messagingSenderId: '488612459446',
    projectId: 'kutubfm-1ef89',
    storageBucket: 'kutubfm-1ef89.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7MPeJl-yr5yQz9FO4UXeESIeU3kpjW00',
    appId: '1:488612459446:ios:54110d06d77de842794717',
    messagingSenderId: '488612459446',
    projectId: 'kutubfm-1ef89',
    storageBucket: 'kutubfm-1ef89.firebasestorage.app',
    iosBundleId: 'com.example.kutubFm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7MPeJl-yr5yQz9FO4UXeESIeU3kpjW00',
    appId: '1:488612459446:ios:54110d06d77de842794717',
    messagingSenderId: '488612459446',
    projectId: 'kutubfm-1ef89',
    storageBucket: 'kutubfm-1ef89.firebasestorage.app',
    iosBundleId: 'com.example.kutubFm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCexInfdWgCXIVvsgMs2DCiv4UkbE5AChI',
    appId: '1:488612459446:web:72fb4756aa41e6cf794717',
    messagingSenderId: '488612459446',
    projectId: 'kutubfm-1ef89',
    authDomain: 'kutubfm-1ef89.firebaseapp.com',
    storageBucket: 'kutubfm-1ef89.firebasestorage.app',
    measurementId: 'G-HGLLPMK5HY',
  );
}
